### PR TITLE
Add maskable icon

### PR DESCRIPTION
**Pull request by NotWoods**
## Overview

Adds a [maskable icon](https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/) so the icon gets a nice background when installed on Android. The icon has been tweaked to have slightly more padding so that the same icon can be used.

[Icon preview](https://maskable.app/?demo=https://raw.githubusercontent.com/NotWoods/pwastats/20a80a8066bf05cba122fa31701b305ffd723210/android-chrome-512x512.png)

---

/CC @cloudfour/pwastats

### CODE REVIEW

**Comment by tylersticka** [comment]
@NotWoods Thanks for the PR!

I notice the new icons have increased in file size, which surprises me given that in most cases the amount of blue space increased (rather than the detail therein). Have these images been optimized?

**Comment by NotWoods** [comment]
They are now :)

**Comment by tylersticka** [comment]
Thanks, @NotWoods!

I'm also noticing some sort of color shift. Before, the background color of the icons was `#456BD9`, matching [our pattern library's palette](https://cloudfour-patterns.netlify.com/). In the new icons, the background color appears to be `#4c6dd2`.

Screen Shot 2019-09-09 at 9 21 21 AM

Looking at the icon in your preview (thank you for that!) I also wonder if we're being a little shy about shrinking to accommodate the new containing shape.

Screen Shot 2019-09-09 at 9 23 04 AM

I think we could shrink it a little more and it might look even nicer?

**Comment by NotWoods** [comment]
I reduced the number of colors to try and minify the image further but it looks like I was a little too eager. I'll play with the icons more and update soon.

**Comment by NotWoods** [comment]
For some reason I can't manage to export an image with the correct colors. I have `#456BD9` in the editor but it exports `#4c6dd2`. (Tried GIMP and Affinity Designer.) Is there a specific color profile I should use?

I'm currently trying to export a slightly smaller image with the original 512x512 logo resized to 408x408 on a background of the same color.

[Preview](https://maskable.app/?demo=https://user-images.githubusercontent.com/1782266/64734728-0b3c5200-d49c-11e9-8e21-62f60b5186f1.png)

android-chrome-512x512

**Comment by tylersticka** [comment]
Thank you for trying! When I have a moment I'll try generating some assets for you that meet those requirements.

**Comment by tylersticka** [comment]
@NotWoods Do these work for you?

android-chrome-192x192
android-chrome-512x512
apple-touch-icon

**Comment by NotWoods** [comment]
Yup, that works! Updated the PR with the new icons.

**Pull request merged**
