### PR TITLE
WIP: GitHub Pages setup

### PR DESCRIPTION
**Pull request by gerardo-rodriguez**
This WIP PR updates the dependencies enabling the `github-pages` gem while commenting out the `jekyll` gem.

I am also prepending the URLs with the `site.github.url` value.

I'd like to test this to see what happens. I enabled (via the repo [settings](https://github.com/cloudfour/pwastats/settings)) GitHub Pages setting `master` as the source. This now exists: https://cloudfour.github.io/pwastats/

You will notice the permalinks, pagination and tags do not work at the moment. Hoping this PR will fix that, but don't know how to test other than merging into `master`.

Also worth noting, after enabling the `github-pages` gem, none of the URLs are correct in my local setup anymore. Images are broken and all of the permalinks, pagination and tag URLs are not correct. Gonna have to try and figure that out too. Not sure why switching that gem affects that, though. More research required.

### CODE REVIEW

**Comment by erikjung** [comment]
I tried a few different things, but was unable to get (`site.github.url`) to output `localhost`. I think we'll need to do one or some of the following:

- use the `environment` property in our config
- have `JEKYLL_GITHUB_TOKEN` exported
- define both `url` and `baseurl` in the config (likely with different values based on the environment)

We want to be able to have the site _just work_ at:

- localhost
- https://cloudfour.github.io/pwastats/
- a third URL? Are we getting a domain?

So this will probably require some `_config.yaml` exploration.

**Comment by tylersticka** [comment]
Also possibly of interest: [this repo](https://github.com/maban/styleguides) has a simpler config and stuff than we do. It looks like they just set `baseurl` to `""`, which might be a fine solution.

> a third URL? Are we getting a domain?

That's for @grigs to decide.

**Comment by erikjung** [comment]
> Also possibly of interest: this repo has a simpler config and stuff than we do. It looks like they just set baseurl to "", which might be a fine solution.

They also use a custom domain, so their templates don't include the references to `site.github.url`. 

Something else to consider WRT to the domain: we have a service worker. Ideally, we would scope it to `/`. We _can_ specify a scope of `/pwastats`, but that will introduce more complications:
- it will not match our local domain
- we'll have to consider anything else that lives under `cloudfour.github.io`

**Comment by gerardo-rodriguez** [comment]
Closing this, no longer relevant.

**Pull request closed without merging**
